### ISSUE TITLE
Elastic-job 有没有任务队列功能？如果有那怎么控制最大注册任务并发数量？

### ISSUE THREAD

**Issue by HappyFullYear** [apache/shardingsphere-elasticjob#2380] opened 2023-12-28 03:53 UTC
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere-elasticjob/issues).
- Read documentation: [ElasticJob Doc](https://shardingsphere.apache.org/elasticjob/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by linghengqian** [comment] 2024-08-05 02:00
- Duplicate of #2381.

**Closed as completed by linghengqian** 2024-08-05 02:00 UTC
Labels: duplicate
