### ISSUE TITLE
任务没有被执行的原因猜测

### ISSUE THREAD

**Issue by wendyqun** [apache/shardingsphere-elasticjob#727] opened 2020-04-11 08:00 UTC
com.dangdang.ddframe.job.lite.internal.shedule.JobTriggerListener    
``` java
@Override
    public void triggerMisfired(final Trigger trigger) {
        if (null != trigger.getPreviousFireTime()) {
            executionService.setMisfire(shardingService.getLocalShardingItems());
        }
    }
```
第一次执行时  trigger.getPreviousFireTime() 必定为null，如果此时执行时发生了 misfire，那么elastic-job就不能设置 misfire状态，导致了任务不会被执行

**Comment by jiang2015** [comment] 2020-07-13 04:47
please assign to me,thanks

**Comment by jiang2015** [comment] 2020-07-13 11:50
this issue how to happen,i have no idea.

**Comment by jiang2015** [comment] 2020-07-15 01:25
@wendyqun this issue how to happen，Do you have the conditions of this issue let us disccuss this problem。

**Comment by terrymanu** [comment] 2020-07-23 04:54
Closed because no response and cannot reproduce.

**Closed as completed by terrymanu** 2020-07-23 04:54 UTC
Labels: invalid
