### ISSUE TITLE
zookeeper主节点挂掉会触发failover

### ISSUE THREAD

**Issue by johnyannj** [apache/shardingsphere-elasticjob#687] opened 2019-10-19 03:33 UTC
作者为zookeeper添加了一个状态监控类RegistryCenterConnectionStateListener

目的是当zookeeper发生故障的时候，暂停任务，当zookeeper恢复连接的时候重新启动任务

临时节点重新注册创建。

问题是：

当zk的leader节点挂掉以后，会触发ConnectionState.RECONNECTED 事件， elastic-job监听此事件会删除、重建任务的instance节点。instance节点的删除操作，会导致其他任务节点监控到执行failover。

instanceService.persistOnline(); 它会调用persistEphemeral创建 XXXX/instances/${instanceId} 临时节点
persistEphemeral里面的逻辑是删除再重建。

public void persistEphemeral(final String key, final String value) {
        try {
            if (isExisted(key)) {
                client.delete().deletingChildrenIfNeeded().forPath(key);
            }
            client.create()
                    .creatingParentsIfNeeded()
                    .withMode(CreateMode.EPHEMERAL)
                    .forPath(key, value.getBytes(Charsets.UTF_8));
            //CHECKSTYLE:OFF
        } catch (final Exception ex) {
            //CHECKSTYLE:ON
            RegExceptionHandler.handleException(ex);
        }
    }

**Comment by terrymanu** [comment] 2020-08-08 13:43
Because the issue is too old and we'd like to use English to communicate now.
I just close the issue. If the issue still exist, please submit a new issue to discuss. 
Thank you very much.

**Closed as completed by terrymanu** 2020-08-08 13:43 UTC
Labels: wontfix
