### ISSUE TITLE
分片建议

### ISSUE THREAD

**Issue by leehom** [apache/shardingsphere-elasticjob#639] opened 2019-03-31 11:21 UTC
目前ej分片比较简单，相当于hint，具体数据由应用解释，很多场景下，例如数据采集一个不断增长的表，需要动态切分数据。建议分片由两步组成，
1. 分配，分片号分配给作业实例，即现在的实现
2. 分片，切分数据，设计如附件
![分片模型](https://user-images.githubusercontent.com/721472/55288435-436a3f80-53ea-11e9-9d34-40c83539a0ab.jpg)

**Comment by terrymanu** [comment] 2020-08-08 13:42
Because the issue is too old and we'd like to use English to communicate now.
I just close the issue. If the issue still exist, please submit a new issue to discuss. 
Thank you very much.

**Closed as completed by terrymanu** 2020-08-08 13:42 UTC
Labels: wontfix
