### ISSUE TITLE
新版本springboot starter依赖在maven仓库中无法找到

### ISSUE THREAD

**Issue by weixq709** [apache/shardingsphere-elasticjob#2463] opened 2024-12-12 01:55 UTC
## Question
新版本的elasticJob文档中未说明有哪些可用的spring boot starter依赖，并且未说明starter要求的springboot版本，能否新增版本对应关系，并列出可用的springboot版本？另外。按照文档中说明的方式，在maven仓库中搜索elasticjob-spring-boot-starter，未找到可用的依赖，类似的依赖是elasticjob-lite-spring-boot-starter，是否文档有误？

**Comment by linghengqian** [comment] 2024-12-12 09:53
- There is no problem with the documentation. For 3.0.4, what you should check out is https://github.com/apache/shardingsphere-elasticjob/tree/3.0.4/elasticjob-lite/elasticjob-lite-spring/elasticjob-lite-spring-boot-starter .
- For the master branch, which is 3.1.0 which is not yet released, this involves https://lists.apache.org/thread/1k6zkvx9dwf2hq2xbb1ngxyxrhw5rd23 . Since ElasticJob Cloud has been removed, most of the dependent GAV information about ElasticJob Lite has been changed.

**Comment by linghengqian** [comment] 2024-12-12 17:29
I think this is a duplicate of issue #2399.

**Closed as completed** 2024-12-12 17:30 UTC
Labels: duplicate, spring
