### ISSUE TITLE
当发布job将mesos集群中的每个节点上的资源全部用完后，注销job再发布新的任务会报错，并且任务会一直处于ready状态。

### ISSUE THREAD

**Issue by yunsongliu** [apache/shardingsphere-elasticjob#454] opened 2017-12-19 03:01 UTC
Please answer these questions before submitting your issue. Thanks!

### Which version of Elastic-Job do you using?
2.1.5
### Expected behavior
注销job再发布job，新的job能正常运行
### Actual behavior
控制台报错，新的job会一直处于ready状态
### Steps to reproduce the behavior
当发布job将mesos集群中的每个节点上的资源全部用完后，注销job再发布新的任务会报错，并且任务会一直处于ready状态。
![image](https://user-images.githubusercontent.com/34666561/34138708-e4171af2-e4ab-11e7-84b2-fdf4e5aa4201.png)

**Comment by terrymanu** [comment] 2020-08-08 13:35
Because the issue is too old and we'd like to use English to communicate now.
I just close the issue.
If the issue still exist, please submit a new issue to discuss. 
Thank you very much.

**Closed as completed by terrymanu** 2020-08-08 13:35 UTC
Labels: wontfix
