### ISSUE TITLE
when do release the new version after the issue was fixed ( Tracing is incompatible with Spring Boot 3.2.x #2401)

### ISSUE THREAD

**Issue by weiro-9-w7** [apache/shardingsphere-elasticjob#2456] opened 2024-10-31 09:30 UTC
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere-elasticjob/issues).
- Read documentation: [ElasticJob Doc](https://shardingsphere.apache.org/elasticjob/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**when do release the new version after the issue was fixed ( Tracing is incompatible with Spring Boot 3.2.x #2401)**

**Comment by linghengqian** [comment] 2024-10-31 10:13
- As an Apache ShardingSphere Committer, releasing new versions has nothing to do with me personally, or even with github.com . I did open https://github.com/apache/shardingsphere-elasticjob/issues/2434, but that's just for discussion purposes. To release a new version, we actually need to comply with https://shardingsphere.apache.org/community/cn/involved/release/elasticjob/ . 
- You should bring the discussion to the shardingsphere mailing list.
- To make a long story short, according to ASF regulations, you need to initiate a discussion mail thread at https://lists.apache.org/list.html?dev@shardingsphere.apache.org and find a ShardingSphere PMC as a release manager. This independent release manager needs to initiate a vote, wait for at least 72 hours, and get the approval votes of 3 ShardingSphere PMCs before releasing a new version.

**Comment by linghengqian** [comment] 2024-11-20 12:16
The issue is closed as it is not related to github.

**Closed as not planned by linghengqian** 2024-11-20 12:16 UTC
Labels: question, release
